services:
  gimos-roofing:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: gimos-roofing-website
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
